# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d07cd1e32877e4e6d27555631de538b3f378e5757895a02fe1e95799c3e096e1045ab29909eddaba807cc0acb47f2e9e8ae14942d7b6deb4067c9bc6daf1bb

test:
  secret_key_base: 50e76de97145fb3f26a8bfcf0773d257853cbf7f9dcf998069df5128634e2a4d843928f906d08c9306283c23eef11ab0c52792a8dfb76efb71791d621a037552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
